--- LazyVim plugin spec for ts-node-highlight.nvim
--- Highlights treesitter nodes from two configurable lists: operands and operators.
---
--- To override node types or highlight groups:
---
---   opts = {
---     operands = {
---       node_types = { "string", "number" },
---       hl_group   = "TsOperandHighlight",
---       enabled    = true,
---     },
---     operators = {
---       node_types = { "operator", "binary_operator" },
---       hl_group   = "TsOperatorHighlight",
---       enabled    = true,
---     },
---   }

return {
  {
    name = "ts-node-highlight.nvim",
    dir = vim.fn.stdpath("config"),

    event = { "BufReadPost", "BufNewFile" },

    opts = {
      -- Both groups are OFF by default; toggle with :TSHighlight operands / operators.
      -- operands = { enabled = true },
      -- operators = { enabled = true },
      operands = {
        node_types = {
          -- Rust Operands
          "integer_literal",
          "float_literal",
          "negative_literal",
          "char_literal",
          "string_literal",
          "raw_string_literal",
          "boolean_literal",
          "identifier",
          "type_identifier",
          "field_identifier",
          "shorthand_field_identifier",
          "primitive_type",

          -- Java Operands
          -- "binary_integer_literal",
          -- "boolean_type",
          -- "character_literal",
          -- "decimal_floating_point_literal",
          -- "decimal_integer_literal",
          -- "false",
          -- "field_identifier",
          -- "floating_point_type",
          -- "hex_floating_point_literal",
          -- "hex_integer_literal",
          -- "identifier",
          -- "integral_type",
          -- "null_literal",
          -- "octal_integer_literal",
          -- "string_literal",
          -- "true",
          -- "type_identifier",
          -- "void_type",
        },
      },
      operators = {
        node_types = {
          -- Rust Operators
          "if",
          "else",
          "for",
          "while",
          "loop",
          "match",
          "break",
          "continue",
          "return",
          "=>",
          "_",
          "pub",
          "static",
          "=",
          "+=",
          "-=",
          "*=",
          "/=",
          "%=",
          "&=",
          "|=",
          "^=",
          "<<=",
          ">>=",
          "&&",
          "||",
          "==",
          "!=",
          "<",
          "<=",
          ">",
          ">=",
          "+",
          "-",
          "*",
          "/",
          "%",
          "&",
          "|",
          "^",
          "<<",
          ">>",
          "!",
          "~",
          "..",
          "..=",
          "...",
          "->",
          "::",
          "?",
          "@",
          "as",
          "ref",
          "move",
          "dyn",
          "impl",
          "fn",
          "struct",
          "enum",
          "trait",
          "mod",
          "use",
          "let",
          "const",
          "type",
          "extern",
          "unsafe",
          "async",
          "await",
          "in",
          "where",
          "union",
          "self",
          "super",
          "crate",
          ";",
          ",",
          ":",
          ".",
          "(",
          "{",
          "[",

          -- Java Operators
          -- "abstract",
          -- "&",
          -- "&=",
          -- "assert",
          -- "break",
          -- "case",
          -- "catch",
          -- "^",
          -- "^=",
          -- "class",
          -- ":",
          -- ",",
          -- "const",
          -- "continue",
          -- "default",
          -- "!=",
          -- "do",
          -- ".",
          -- "&&",
          -- "::",
          -- "==",
          -- "<<",
          -- "<<=",
          -- "--",
          -- "||",
          -- "++",
          -- ">>",
          -- ">>=",
          -- "else",
          -- "enum",
          -- "=",
          -- "!",
          -- "extends",
          -- "final",
          -- "finally",
          -- "for",
          -- "goto",
          -- "if",
          -- "implements",
          -- "import",
          -- "instanceof",
          -- "interface",
          -- "->",
          -- "<",
          -- "<=",
          -- "-",
          -- "-=",
          -- "native",
          -- "new",
          -- "{",
          -- "(",
          -- "[",
          -- "package",
          -- "%",
          -- "%=",
          -- "|",
          -- "|=",
          -- "+",
          -- "+=",
          -- "private",
          -- "protected",
          -- "public",
          -- "?",
          -- "return",
          -- ";",
          -- "/",
          -- "/=",
          -- "*",
          -- "*=",
          -- "static",
          -- "strictfp",
          -- "super",
          -- "switch",
          -- "synchronized",
          -- "this",
          -- "throw",
          -- "throws",
          -- "~",
          -- "transient",
          -- ">>>=",
          -- "try",
          -- ">",
          -- ">=",
          -- "volatile",
          -- "while",
        },
      },
    },

    config = function(_, opts)
      require("ts-node-highlight").setup(opts)
    end,

    keys = {
      {
        "<leader>uho",
        function()
          require("ts-node-highlight").toggle("operands")
        end,
        desc = "Toggle TS operand highlight",
      },
      {
        "<leader>uhO",
        function()
          require("ts-node-highlight").toggle("operators")
        end,
        desc = "Toggle TS operator highlight",
      },
      {
        "<leader>uhr",
        function()
          require("ts-node-highlight").refresh()
        end,
        desc = "Refresh TS node highlight",
      },
      -- Visual-mode range highlights (select lines, then press the mapping).
      {
        "<leader>uho",
        ":<C-u>TSHighlight range operands<CR>",
        mode = "x",
        desc = "Toggle TS operand highlight for range",
      },
      {
        "<leader>uhO",
        ":<C-u>TSHighlight range operators<CR>",
        mode = "x",
        desc = "Toggle TS operator highlight for range",
      },
      {
        "<leader>uhx",
        function()
          require("ts-node-highlight").clear_ranges()
        end,
        desc = "Clear all TS range highlights",
      },
      {
        "<leader>uhc",
        function()
          require("ts-node-highlight").clear()
        end,
        desc = "Clear all TS highlights",
      },
    },
  },
}
